table Client_bridge_dim
	lineageTag: fde77420-9689-4b20-98b2-6c5bb3ba98fc

	column Country
		dataType: string
		lineageTag: 1d2595ec-0d07-4eb4-a726-0af860f03f4d
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column 'Client ID'
		dataType: string
		lineageTag: ee2e1b4a-aa40-4e52-b45b-8eba3314366a
		summarizeBy: none
		sourceColumn: Client ID

		annotation SummarizationSetBy = Automatic

	column ClientBridge_key
		dataType: string
		lineageTag: ce83379d-b031-4546-a16f-05b7daf43dc8
		summarizeBy: none
		sourceColumn: ClientBridge_key

		annotation SummarizationSetBy = Automatic

	partition Client_bridge_dim = m
		mode: import
		source =
				let
				    Source = Client_dim,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Country", "Client ID"}),
				    #"Inserted Merged Column" = Table.AddColumn(#"Removed Other Columns", "ClientBridge_key", each Text.Combine({[Country], [Client ID]}, "-"), type text),
				    #"Removed Duplicates" = Table.Distinct(#"Inserted Merged Column")
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

