table 'Payment Status_fct'
	lineageTag: 0d7f5113-556c-4d5e-a5e9-b917358c5eec

	column Country
		dataType: string
		lineageTag: dde2d445-e19f-4094-bc84-49d936a3a158
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column 'Client ID'
		dataType: string
		lineageTag: be439c74-c58e-4034-a541-75455a300a95
		summarizeBy: none
		sourceColumn: Client ID

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Quarter'
		dataType: string
		lineageTag: a3aa7374-0763-46a1-91f1-e4e2269547a9
		summarizeBy: none
		sourceColumn: Fiscal Quarter

		annotation SummarizationSetBy = Automatic

	column 'Payment Status'
		dataType: string
		lineageTag: b10a385a-f7b6-4d46-b00c-6a6d58369477
		summarizeBy: none
		sourceColumn: Payment Status

		annotation SummarizationSetBy = Automatic

	column ClientBridge_key
		dataType: string
		lineageTag: b0a70a76-81ec-46e1-8190-7daab6d7192d
		summarizeBy: none
		sourceColumn: ClientBridge_key

		annotation SummarizationSetBy = Automatic

	column 'Quarter Start'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 20d67fd9-d8a4-47e0-98b2-a80a3b77a81c
		summarizeBy: none
		sourceColumn: Quarter Start

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'Payment Status_fct' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\dplaw\Desktop\Pbi climb\Payment Status.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Country", type text}, {"Client ID", type text}, {"Fiscal Quarter", type text}, {"Payment Status", type text}}),
				    #"Inserted Merged Column" = Table.AddColumn(#"Changed Type1", "ClientBridge_key", each Text.Combine({[Country], [Client ID]}, "-"), type text),
				    #"Added Conditional Column" = Table.AddColumn(#"Inserted Merged Column", "Quarter Start ", each if [Fiscal Quarter] = "Q1" then #date(2025, 1, 1) else if [Fiscal Quarter] = "Q2" then #date(2025, 4, 1) else if [Fiscal Quarter] = "Q3" then #date(2025, 7, 1) else if [Fiscal Quarter] = "Q4" then #date(2025, 10, 1) else null),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Conditional Column",{{"Quarter Start ", "Quarter Start"}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Renamed Columns",{{"Quarter Start", type date}})
				in
				    #"Changed Type2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

