table 'Targets Fy25_fct'
	lineageTag: 7ed6416a-fc4d-48ef-8cef-58243ef88b41

	column Country
		dataType: string
		lineageTag: dfa77f7d-f7eb-4570-a17d-c1f927a500f8
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column 'Client ID'
		dataType: string
		lineageTag: aa9c208f-760a-4e89-a668-604b5446a1a5
		summarizeBy: none
		sourceColumn: Client ID

		annotation SummarizationSetBy = Automatic

	column Client_Key
		dataType: string
		lineageTag: e6a975bd-39b9-4e8b-a8ea-9de6962353ad
		summarizeBy: none
		sourceColumn: Client_Key

		annotation SummarizationSetBy = Automatic

	column FyEnd
		dataType: dateTime
		formatString: Long Date
		lineageTag: b4e8714f-b1fe-4fb4-b9af-db04ba9372a1
		summarizeBy: none
		sourceColumn: FyEnd

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Business Unit'
		dataType: string
		lineageTag: eb84fe7e-e02b-4b39-a2eb-d6cd7cb6b42c
		summarizeBy: none
		sourceColumn: Business Unit

		annotation SummarizationSetBy = Automatic

	column 'Sales Target in USD'
		dataType: double
		lineageTag: becac328-30e9-4040-ab12-9f05a135efb8
		summarizeBy: sum
		sourceColumn: Sales Target in USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Targets Fy25_fct' = m
		mode: import
		source =
				let
				    Source = MySQL.Database(
				        "localhost",
				        "sales",
				        [
				            ReturnSingleDatabase = true,
				            Query = "SELECT * FROM sales.targets25"
				        ]
				    ),
				    InsertedMergedColumn = Table.AddColumn(Source, "Client_Key", each Text.Combine({[Country], [Business Unit], [Client ID]}, "-"), type text),
				    FY = Table.AddColumn(InsertedMergedColumn, "FyEnd", each #date(2025, 12, 31), type date)
				in
				    FY

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

